# TAUSIK CLI wrapper for PowerShell - always uses .tausik/venv Python.
# Generated by bootstrap. Do not edit manually.
#
# Why this exists next to tausik.cmd: cmd.exe parses its command line before
# the .cmd body runs, and a newline inside an argument ENDS that command line.
# Every multi-line value passed through the .cmd wrapper - task log messages,
# --evidence blocks, memory content - silently arrived as its first line only,
# and the caller had no way to notice. PowerShell hands arguments to a native
# executable as an array (@args), so the text survives intact.

$ErrorActionPreference = 'Stop'
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectDir = Split-Path -Parent $ScriptDir

# Force UTF-8 stdio so Unicode output never hits a cp1251/cp1252 encoder.
$env:PYTHONUTF8 = '1'

# IDE list injected from bootstrap_config.IDE_DIRS (single source of truth).
$IdeList = '__IDE_LIST__' -split ' '
$Scripts = $null
foreach ($ide in $IdeList) {
    if (-not $Scripts) {
        $candidate = Join-Path $ProjectDir ".$ide\scripts"
        if (Test-Path $candidate) { $Scripts = $candidate }
    }
}
if (-not $Scripts) {
    Write-Error "Error: no scripts dir found (none of: $IdeList under .<ide>\scripts)"
    exit 1
}

$Python = Join-Path $ScriptDir 'venv\Scripts\python.exe'
if (-not (Test-Path $Python)) { $Python = 'python' }

& $Python (Join-Path $Scripts 'project.py') @args
exit $LASTEXITCODE
