"""memory-route-gate: the deny-list, the gate, and the PreToolUse hook.

The load-bearing test in this file is `TestTausikOwnedNotBlocked`. The rest
verify the feature; that one verifies the framework did not fence itself in.
`.cursorrules`, `.windsurfrules`, `CLAUDE.md`, `AGENTS.md`, `QWEN.md` are
generated by `bootstrap --ide all`, and this repository gitignores every one of
them — so a deny-list entry that swallowed an adapter would pass CI here and
break `bootstrap` only in a project that tracks its generated files. The test
asserts the invariant that makes that impossible.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys

import pytest

sys.path.insert(
    0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "scripts")
)

from memory_sinks import (  # noqa: E402
    DEFAULT_SINKS,
    SCOPE_HOME,
    SCOPE_TREE,
    SinkRule,
    find_foreign_sinks,
    glob_match,
    is_absolute,
    is_foreign_sink,
    normalize,
    redirect_message,
    sinks_from_config,
    tausik_owned_paths,
)

_REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_HOOK = os.path.join(_REPO, "scripts", "hooks", "memory_pretool_block.py")


class TestGlob:
    @pytest.mark.parametrize(
        "pattern,path",
        [
            (".claude/**/memory/**", ".claude/memory/x.md"),
            (".claude/**/memory/**", ".claude/projects/foo/memory/x.md"),
            (".claude/**/memory/**", ".claude/harness/a/b/memory/deep/x.md"),
            (".cursor/rules/**", ".cursor/rules/a.mdc"),
            (".cursor/rules/**", ".cursor/rules/nested/a.mdc"),
            (".aider*", ".aider.conf.yml"),
            (".aider*", ".aider"),
            (".github/copilot-instructions.md", ".github/copilot-instructions.md"),
        ],
    )
    def test_matches(self, pattern, path):
        assert glob_match(pattern, path)

    @pytest.mark.parametrize(
        "pattern,path",
        [
            (".claude/**/memory/**", ".claude/memory.md"),
            (".claude/**/memory/**", ".claude/memoryold/x.md"),
            (".claude/**/memory/**", ".claude/somememory/x.md"),
            (".cursor/rules/**", ".cursor/scripts/a.py"),
            (".cursor/rules/**", ".cursor/rulesets/a.mdc"),
            (".aider*", "src/.aider.py"),
            (".github/copilot-instructions.md", ".github/workflows/tests.yml"),
        ],
    )
    def test_does_not_match(self, pattern, path):
        assert not glob_match(pattern, path)

    def test_double_star_consumes_zero_segments(self):
        # `.claude/memory/x.md` has nothing between `.claude` and `memory`.
        assert glob_match("a/**/b/**", "a/b/c")

    def test_normalize_is_case_and_separator_insensitive(self):
        assert normalize("A\\B\\..\\C") == "a/c"


class TestPathShapeDoesNotDependOnTheRunningPlatform:
    """Both answers below used to change with the OS reading the string.

    `normalize` collapsed `..` through `os.path.normpath`, which treats a
    backslash as a separator only on Windows; `_tree_relative` asked
    `os.path.isabs`, which calls `d:/proj` relative anywhere but Windows. Both
    inputs arrive as TEXT — from a config file, an environment variable, a hook
    payload written by another machine — so the platform that happens to be
    reading is the wrong thing to ask. These assertions carry no `sys.platform`
    on purpose: identical expectations on every OS is the whole property.
    """

    def test_backslashes_collapse_the_same_everywhere(self):
        assert normalize("A\\B\\..\\C") == "a/c"
        assert normalize("a/b\\..\\c") == "a/c"
        assert normalize("a\\b/../c") == "a/c"
        assert ".." not in normalize("x\\y\\..\\z")

    def test_a_drive_letter_is_absolute_everywhere(self):
        assert is_absolute("d:/proj/core")
        assert is_absolute("C:\\proj\\core")
        assert is_absolute("/var/lib/x")
        assert is_absolute("\\\\server\\share")
        assert is_absolute("//server/share")

    def test_what_is_not_absolute_stays_relative(self):
        assert not is_absolute("proj/core")
        assert not is_absolute(".clinerules")
        assert not is_absolute("")
        # Drive-RELATIVE: `C:x` means "x on drive C's current directory", which
        # is not an absolute path even on Windows.
        assert not is_absolute("C:x")

    def test_a_windows_project_dir_still_yields_a_relative_display_path(self):
        """The Linux half of convention #282: the reader gets a pasteable path."""
        rule = DEFAULT_SINKS[0]
        msg = redirect_message(
            [("d:/proj/core/.clinerules", rule)], ".tausik/tausik", "d:/proj/core"
        )
        assert "  .clinerules  ->" in msg, msg
        assert "d:/proj/core/.clinerules" not in msg, msg


class TestTreeSinks:
    def test_blocks_cursor_rules(self, tmp_path):
        rule = is_foreign_sink(".cursor/rules/learned.mdc", str(tmp_path))
        assert rule is not None and rule.name == "cursor_rules"

    def test_blocks_absolute_path_inside_project(self, tmp_path):
        target = os.path.join(str(tmp_path), ".github", "copilot-instructions.md")
        assert is_foreign_sink(target, str(tmp_path)) is not None

    def test_ignores_path_outside_project(self, tmp_path):
        # An identically-named file in ANOTHER repository is not this project's
        # business — the gate must not judge trees it does not own.
        other = os.path.join(str(tmp_path.parent), "elsewhere", ".clinerules")
        assert is_foreign_sink(other, os.path.join(str(tmp_path), "proj")) is None

    def test_case_insensitive(self, tmp_path):
        assert is_foreign_sink(".Cursor/Rules/A.MDC", str(tmp_path)) is not None

    def test_allow_list_exempts(self, tmp_path):
        assert (
            is_foreign_sink(".cursor/rules/a.mdc", str(tmp_path), allow=[".cursor/rules/**"])
            is None
        )

    def test_find_preserves_input_order(self, tmp_path):
        paths = ["README.md", ".aider.conf.yml", "scripts/x.py", ".clinerules"]
        hits = find_foreign_sinks(paths, str(tmp_path))
        assert [p for p, _ in hits] == [".aider.conf.yml", ".clinerules"]


class TestHomeSink:
    def test_blocks_home_claude_memory(self, monkeypatch, tmp_path):
        monkeypatch.setenv("HOME", str(tmp_path))
        monkeypatch.setenv("USERPROFILE", str(tmp_path))
        target = os.path.join(str(tmp_path), ".claude", "projects", "p", "memory", "x.md")
        rule = is_foreign_sink(target)
        assert rule is not None and rule.scope == SCOPE_HOME

    def test_mixed_case_home_memory_still_blocked(self, monkeypatch, tmp_path):
        monkeypatch.setenv("HOME", str(tmp_path))
        monkeypatch.setenv("USERPROFILE", str(tmp_path))
        target = os.path.join(str(tmp_path), ".claude", "harness", "h", "MeMoRy", "x.md")
        assert is_foreign_sink(target) is not None

    def test_home_claude_non_memory_allowed(self, monkeypatch, tmp_path):
        monkeypatch.setenv("HOME", str(tmp_path))
        monkeypatch.setenv("USERPROFILE", str(tmp_path))
        target = os.path.join(str(tmp_path), ".claude", "settings.json")
        assert is_foreign_sink(target) is None


class TestTausikOwnedNotBlocked:
    """The framework must not fence in its own deployment targets."""

    def test_no_sink_matches_a_tausik_rules_file(self):
        _dirs, files = tausik_owned_paths()
        assert files, "IDE_REGISTRY exposed no rules_file — the guard would be vacuous"
        for rules_file in files:
            assert is_foreign_sink(rules_file, "/proj") is None, (
                f"{rules_file} is generated by `bootstrap --ide all`; listing it as a "
                f"foreign sink would make the framework block its own bootstrap"
            )

    def test_no_sink_matches_an_ide_config_dir_root(self):
        dirs, _files = tausik_owned_paths()
        assert dirs
        for cfg_dir in dirs:
            for probe in (cfg_dir, f"{cfg_dir}/mcp.json", f"{cfg_dir}/skills/x/SKILL.md"):
                assert is_foreign_sink(probe, "/proj") is None, f"{probe} is TAUSIK-deployed"

    def test_cursor_rules_still_foreign_despite_owned_parent(self):
        # Precedence, stated in memory_sinks: an explicit sink pattern wins over
        # the owned-tree carve-out. TAUSIK deploys .cursor/ but never .cursor/rules/.
        assert is_foreign_sink(".cursor/rules/x.mdc", "/proj") is not None

    def test_tausik_memory_db_and_changelog_are_not_sinks(self):
        for legit in (".tausik/tausik.db", "CHANGELOG.md", "docs/ru/memory.md", "scripts/x.py"):
            assert is_foreign_sink(legit, "/proj") is None


class TestConfigPolicy:
    def test_absent_block_uses_defaults(self):
        sinks, allow, err = sinks_from_config({})
        assert sinks == DEFAULT_SINKS and allow == () and err is None

    def test_extra_sinks_append_never_replace(self):
        sinks, _allow, err = sinks_from_config(
            {"gates": {"memory_route": {"extra_sinks": [".myagent/memory/**"]}}}
        )
        assert err is None
        assert len(sinks) == len(DEFAULT_SINKS) + 1
        assert all(d in sinks for d in DEFAULT_SINKS)
        assert is_foreign_sink(".myagent/memory/a.md", "/proj", sinks=sinks) is not None

    def test_allow_list_parsed(self):
        _sinks, allow, err = sinks_from_config(
            {"gates": {"memory_route": {"allow": [".cursor/rules/team.mdc"]}}}
        )
        assert err is None and allow == (".cursor/rules/team.mdc",)

    @pytest.mark.parametrize(
        "block",
        ["nope", {"extra_sinks": "str-not-list"}, {"allow": [""]}, {"extra_sinks": [1]}],
    )
    def test_malformed_block_reports_error_and_keeps_defaults(self, block):
        sinks, _allow, err = sinks_from_config({"gates": {"memory_route": block}})
        assert err, "a malformed policy must be reported, not silently ignored"
        assert sinks == DEFAULT_SINKS


class TestRedirectMessage:
    def test_names_path_host_and_the_command(self):
        rule = DEFAULT_SINKS[0]
        msg = redirect_message([("x.md", rule)], ".tausik/tausik")
        assert "x.md" in msg and rule.host in msg
        assert ".tausik/tausik memory add" in msg
        assert "gates.memory_route.allow" in msg

    def test_path_is_project_relative_with_one_separator_style(self):
        # `os.path.join` of a '/'-style CLAUDE_PROJECT_DIR with a relative target
        # produced `d:/Work/.../core\.clinerules` — mixed separators in the one
        # line the reader must act on (convention #282). Caught by dogfooding.
        rule = DEFAULT_SINKS[0]
        joined = os.path.join("d:/proj/core", ".clinerules")
        msg = redirect_message([(joined, rule)], ".tausik/tausik", "d:/proj/core")
        assert "  .clinerules  ->" in msg
        assert "\\" not in msg.split("->")[0]


# --- Gate -------------------------------------------------------------------


def _git(cwd, *args):
    return subprocess.run(
        ["git", *args],
        cwd=cwd,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=30,
        stdin=subprocess.DEVNULL,
    )


@pytest.fixture
def repo(tmp_path):
    root = tmp_path / "proj"
    root.mkdir()
    _git(str(root), "init", "-q")
    _git(str(root), "config", "user.email", "t@t.t")
    _git(str(root), "config", "user.name", "t")
    (root / ".tausik").mkdir()
    (root / "README.md").write_text("x\n", encoding="utf-8")
    _git(str(root), "add", "-A")
    _git(str(root), "commit", "-qm", "init")
    return root


class TestGate:
    def test_clean_tree_passes(self, repo):
        from gate_memory_route import scan_tree

        passed, out = scan_tree(str(repo), {})
        assert passed, out

    def test_foreign_sink_in_tree_blocks(self, repo):
        from gate_memory_route import scan_tree

        (repo / ".cursor" / "rules").mkdir(parents=True)
        (repo / ".cursor" / "rules" / "learned.mdc").write_text("db host is x\n", encoding="utf-8")
        passed, out = scan_tree(str(repo), {})
        assert not passed
        assert ".cursor/rules/learned.mdc" in out.replace("\\", "/")
        assert "memory add" in out

    def test_brand_new_sink_directory_is_not_collapsed_away(self, repo):
        # Regression: `git status --porcelain` collapses a wholly-untracked
        # directory to `?? .cursor/`, which matches no sink pattern — so the
        # FIRST write into a fresh sink dir, the likeliest shape of this defect,
        # used to pass. The gate must ask for `--untracked-files=all`.
        from verify_git_diff import uncommitted_changes

        (repo / ".cursor" / "rules").mkdir(parents=True)
        (repo / ".cursor" / "rules" / "learned.mdc").write_text("x\n", encoding="utf-8")
        collapsed = uncommitted_changes(root=str(repo))
        assert collapsed == [".cursor/"], f"git behaviour changed: {collapsed}"
        expanded = uncommitted_changes(root=str(repo), untracked="all")
        assert ".cursor/rules/learned.mdc" in expanded

    def test_legit_change_passes(self, repo):
        from gate_memory_route import scan_tree

        (repo / "scripts").mkdir()
        (repo / "scripts" / "x.py").write_text("print(1)\n", encoding="utf-8")
        passed, out = scan_tree(str(repo), {})
        assert passed, out

    def test_allow_config_unblocks(self, repo):
        from gate_memory_route import scan_tree

        (repo / ".clinerules").write_text("x\n", encoding="utf-8")
        assert not scan_tree(str(repo), {})[0]
        cfg = {"gates": {"memory_route": {"allow": [".clinerules"]}}}
        assert scan_tree(str(repo), cfg)[0]

    def test_malformed_policy_fails_closed(self, repo):
        from gate_memory_route import scan_tree

        passed, out = scan_tree(str(repo), {"gates": {"memory_route": "on"}})
        assert not passed and "fail-closed" in out

    def test_non_repo_is_inert_not_a_failure(self, tmp_path):
        from gate_memory_route import scan_tree

        plain = tmp_path / "plain"
        plain.mkdir()
        passed, out = scan_tree(str(plain), {})
        assert passed and "not a git repository" in out

    def test_registered_in_registry_with_blocking_severity(self):
        from gate_registry import GATE_REGISTRY, PHASE_SCOPED

        spec = GATE_REGISTRY["memory_route"]
        assert spec.phase == PHASE_SCOPED
        assert spec.default_config["severity"] == "block"
        assert spec.default_config["enabled"] is True
        assert "task-done" in spec.default_config["trigger"]
        assert "commit" in spec.default_config["trigger"]

    def test_registry_impl_resolves(self):
        from gate_registry import impl_for

        assert impl_for("memory_route") is not None

    def test_appears_in_default_gates(self):
        from default_gates import UNIVERSAL_GATES

        assert "memory_route" in UNIVERSAL_GATES


# --- PreToolUse hook --------------------------------------------------------


def _run_hook(event: dict, project_dir: str, env_extra: dict | None = None):
    env = dict(os.environ)
    env["CLAUDE_PROJECT_DIR"] = project_dir
    env.pop("TAUSIK_SKIP_HOOKS", None)
    env.pop("TAUSIK_SKIP_MEMORY_HOOK", None)
    env.update(env_extra or {})
    return subprocess.run(
        [sys.executable, _HOOK],
        input=json.dumps(event),
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        env=env,
        timeout=60,
    )


class TestHook:
    def test_blocks_write_to_tree_sink(self, repo):
        r = _run_hook(
            {
                "tool_name": "Write",
                "tool_input": {"file_path": str(repo / ".cursor" / "rules" / "x.mdc")},
            },
            str(repo),
        )
        assert r.returncode == 2, r.stdout + r.stderr
        assert "memory add" in r.stderr

    def test_blocks_bash_heredoc_into_home_memory(self, repo, tmp_path):
        home = tmp_path / "home"
        (home / ".claude" / "projects" / "p" / "memory").mkdir(parents=True)
        target = home / ".claude" / "projects" / "p" / "memory" / "n.md"
        cmd = f"cat >> {target.as_posix()} <<'EOF'\nproject fact\nEOF"
        r = _run_hook(
            {"tool_name": "Bash", "tool_input": {"command": cmd}},
            str(repo),
            {"HOME": str(home), "USERPROFILE": str(home)},
        )
        assert r.returncode == 2, r.stdout + r.stderr

    def test_blocks_bash_redirect_into_tree_sink(self, repo):
        r = _run_hook(
            {"tool_name": "Bash", "tool_input": {"command": "echo x > .clinerules"}},
            str(repo),
        )
        assert r.returncode == 2, r.stdout + r.stderr

    def test_allows_ordinary_write(self, repo):
        r = _run_hook(
            {"tool_name": "Write", "tool_input": {"file_path": str(repo / "scripts" / "x.py")}},
            str(repo),
        )
        assert r.returncode == 0, r.stdout + r.stderr

    def test_allows_ordinary_bash(self, repo):
        r = _run_hook(
            {"tool_name": "Bash", "tool_input": {"command": "pytest -q"}},
            str(repo),
        )
        assert r.returncode == 0, r.stdout + r.stderr

    def test_allows_tausik_memory_add(self, repo):
        r = _run_hook(
            {
                "tool_name": "Bash",
                "tool_input": {"command": '.tausik/tausik memory add --type pattern --title "x"'},
            },
            str(repo),
        )
        assert r.returncode == 0, r.stdout + r.stderr

    def test_allows_bootstrap_writing_its_own_adapter(self, repo):
        # `bootstrap --ide all` regenerates .cursorrules / AGENTS.md. If the hook
        # blocked those, the framework could not deploy itself.
        for owned in (".cursorrules", "AGENTS.md", "CLAUDE.md", "QWEN.md"):
            r = _run_hook(
                {"tool_name": "Write", "tool_input": {"file_path": str(repo / owned)}},
                str(repo),
            )
            assert r.returncode == 0, f"{owned}: {r.stderr}"

    def test_a_quoted_mention_is_not_a_write(self, repo):
        # Found by dogfooding: the hook blocked a diagnostic `python -c` that
        # merely QUOTED a sink path, over the garbage target
        # `.cursor/rules/a.mdc/"',`. The command does not tokenize, so the
        # parser's regex fallback guessed — cheap for QG-0, expensive here,
        # where the block accuses the agent of leaking knowledge and the only
        # exits are an untrue marker or a permanent config exemption.
        for cmd in (
            "python -c \"print('> .cursor/rules/a.mdc')\"",
            "grep -n '> .clinerules' README.md",
            "echo 'see .cursor/rules/a.mdc for details'",
            # Unparseable: an unbalanced quote sends the parser to its
            # over-detecting fallback, which is what actually fired live.
            "awk '{print $1} > .clinerules",
            "sed 's/x/y/ > .cursor/rules/a.mdc",
        ):
            r = _run_hook({"tool_name": "Bash", "tool_input": {"command": cmd}}, str(repo))
            assert r.returncode == 0, f"{cmd!r} blocked: {r.stderr}"

    def test_real_bash_writes_are_still_blocked(self, repo):
        # The negative half of the same change: dropping the fallback must not
        # drop anything the parser actually resolved.
        for cmd in (
            "printf x > .clinerules",
            "tee .cursor/rules/a.mdc",
            "echo x >> .github/copilot-instructions.md",
        ):
            r = _run_hook({"tool_name": "Bash", "tool_input": {"command": cmd}}, str(repo))
            assert r.returncode == 2, f"{cmd!r} not blocked: {r.stdout}"

    def test_qg0_parser_contract_is_unchanged(self):
        # bash_write_gate has a different cost of error, so its answer — the
        # over-detecting one — must stay bit-for-bit what it was.
        sys.path.insert(0, os.path.join(_REPO, "scripts", "hooks"))
        from bash_write_parse import (
            CONFIDENCE_PARSED,
            CONFIDENCE_REGEX_FALLBACK,
            write_targets,
            write_targets_with_confidence,
        )

        # An unbalanced quote shlex cannot close — the shape behind the live
        # false positive, where the fallback's "path" carried the trailing
        # quote-and-comma junk of the surrounding source.
        unparseable = "awk '{print $1} > .clinerules"
        assert write_targets(unparseable), "QG-0 must still over-detect here"
        targets, conf = write_targets_with_confidence(unparseable)
        assert conf == CONFIDENCE_REGEX_FALLBACK and targets == write_targets(unparseable)

        parsed = "printf x > .clinerules"
        targets, conf = write_targets_with_confidence(parsed)
        assert conf == CONFIDENCE_PARSED and targets == [".clinerules"] == write_targets(parsed)

    def test_interpreter_wrapper_no_longer_hides_the_target(self):
        # This test was written one task earlier PINNING the opposite — that a
        # `bash -c` wrapper yielded nothing — precisely so that the day someone
        # taught the parser to recurse, the change would announce itself instead
        # of passing silently. It did exactly that, and is inverted here.
        sys.path.insert(0, os.path.join(_REPO, "scripts", "hooks"))
        from bash_write_parse import write_targets

        assert write_targets("bash -c 'printf x > .clinerules'") == [".clinerules"]
        assert write_targets('sh -c "echo x > .cursor/rules/a.mdc"') == [".cursor/rules/a.mdc"]
        assert write_targets("printf x > .clinerules") == [".clinerules"]

    def test_blocks_write_hidden_behind_a_shell_wrapper(self, repo):
        r = _run_hook(
            {"tool_name": "Bash", "tool_input": {"command": "bash -c 'echo x > .clinerules'"}},
            str(repo),
        )
        assert r.returncode == 2, r.stdout + r.stderr

    def test_skip_flag_allows(self, repo):
        r = _run_hook(
            {"tool_name": "Write", "tool_input": {"file_path": str(repo / ".clinerules")}},
            str(repo),
            {"TAUSIK_SKIP_MEMORY_HOOK": "1"},
        )
        assert r.returncode == 0

    def test_not_a_tausik_project_is_ignored(self, tmp_path):
        plain = tmp_path / "plain"
        plain.mkdir()
        r = _run_hook(
            {"tool_name": "Write", "tool_input": {"file_path": str(plain / ".clinerules")}},
            str(plain),
        )
        assert r.returncode == 0

    def test_malformed_stdin_does_not_block(self, repo):
        env = dict(os.environ)
        env["CLAUDE_PROJECT_DIR"] = str(repo)
        r = subprocess.run(
            [sys.executable, _HOOK],
            input="{not json",
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            env=env,
            timeout=60,
        )
        assert r.returncode == 0

    def test_is_in_claude_memory_stays_narrow(self, monkeypatch, tmp_path):
        # memory_posttool_audit uses this to decide whether to scan CONTENT for
        # project markers. Widening it to every sink would repoint that audit.
        sys.path.insert(0, os.path.join(_REPO, "scripts", "hooks"))
        from memory_pretool_block import is_in_claude_memory

        monkeypatch.setenv("HOME", str(tmp_path))
        monkeypatch.setenv("USERPROFILE", str(tmp_path))
        assert is_in_claude_memory(str(tmp_path / ".claude" / "projects" / "p" / "memory" / "x.md"))
        assert not is_in_claude_memory(".cursor/rules/x.mdc")


class TestHookRegistration:
    def test_claude_settings_matcher_includes_bash(self):
        sys.path.insert(0, os.path.join(_REPO, "bootstrap"))
        from bootstrap_hooks import build_hooks_dict

        hooks = build_hooks_dict(lambda script, suffix="": f"python {script}{suffix}")
        entries = [
            e
            for e in hooks["PreToolUse"]
            if any("memory_pretool_block.py" in h["command"] for h in e["hooks"])
        ]
        assert len(entries) == 1
        assert "Bash" in entries[0]["matcher"]

    def test_sink_rules_are_wellformed(self):
        names = [r.name for r in DEFAULT_SINKS]
        assert len(names) == len(set(names)), "duplicate sink name"
        for r in DEFAULT_SINKS:
            assert isinstance(r, SinkRule)
            assert r.scope in (SCOPE_TREE, SCOPE_HOME)
            assert r.pattern == normalize(r.pattern) or "*" in r.pattern
            assert r.host and r.why

    def test_litmus_block_reaches_every_generated_rule_file(self):
        sys.path.insert(0, os.path.join(_REPO, "bootstrap"))
        from bootstrap_templates import build_full_body

        for tier in ("minimal", "standard", "full"):
            body = build_full_body("p", ["python"], "Agent", ".claude", context_tier=tier)
            assert "memory_route" in body, f"tier={tier} lost the litmus block"
            assert ".cursor/rules/" in body, f"tier={tier}"
